# Generated by Django 4.2 on 2024-05-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='user id')),
                ('token_type', models.PositiveSmallIntegerField(choices=[(1, 'access token'), (2, 'refresh token')], verbose_name='token type')),
                ('uuid', models.UUIDField(db_index=True, unique=True, verbose_name='uuid')),
                ('device_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='device login count')),
            ],
            options={
                'verbose_name': 'UserAuth',
                'verbose_name_plural': 'UserAuths',
                'ordering': ('-id',),
            },
        ),
    ]
